apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0r7w
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kkoj-tenant/rhtap-demo-app/hacbs-test-project-0r7w@sha256:fd62f826888971fa99be03e3ec901165339c3d45c19550779ad3be96169f2fcb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
