apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0r7w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0r7w
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0r7w
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0r7w
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0r7w
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kkoj-tenant/rhtap-demo-app/hacbs-test-project-0r7w@sha256:fd62f826888971fa99be03e3ec901165339c3d45c19550779ad3be96169f2fcb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
